blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/avishayil/react-native-user-avatar/discussions
    about: Ask questions and discuss usage with the community.
